### ISSUE TITLE
[LFT]: Designer looking for a team

### ISSUE THREAD

**Issue by ndreij** [ethb3rlin/find-a-team#10]
## Background

Portfolio: [ndreij.xyz](http://ndreij.xyz)

- A designer with UX / motion / presentation skills, just back from ETHWarsaw (check out [the deck](https://docs.google.com/presentation/d/1K6VbDI9UphReavi8bMg4Rg8FhcgEXXCAO7YVighRhrA/edit#slide=id.p) I did for a project there)
- Supporting dozens of startups with visual storytelling and product design
- Reading vitalik.ca around autumn'21 made me realise not everyone here is after chasing profits
- I want to find a community, do good for the society and get my hands dirty, building

## Skills

- [x] Design, User Experience
- [x] Webflow, Figma, After Effects, React
- [ ] Core Blockchain Development (Go, C++, Rust)
- [ ] Smart Contracts (Solidity, Vyper)
- [ ] DApps, Web3.JS (JavaScript, CSS)
- [ ] Blockchain Operations, Infrastructure
- [ ] Game theory, Crypto-Economics
- [ ] Project Management

## Hackathon project

This is the track I would like to target:

> Even the Odds: Empowering the underprivileged. Topcis: Social Justice, Inclusion, Sustainability, Public Goods.

## Communication

_Matrix handle_: @0x79616b

**Comment by EdsonAlcala** [comment]
hey hi ! I'm a smart contract and full stack developer, looking for a team. Been in the space since 2017. I saw 2 other people that are looking for teams. Check https://github.com/ethb3rlin/find-a-team/issues/23 and https://github.com/ethb3rlin/find-a-team/issues/19 maybe we can team?
