### ISSUE TITLE
[LFT]: Fullstack Developer with Solidity experience looking for a Team

### ISSUE THREAD

**Issue by niklasnatter** [ethb3rlin/find-a-team#16]
## Background

_Talk a little about yourself:_

- [ ] **_Who you are_:** I am a 27 year old software engineer living in Berlin. I work for an open source content management system and have production experience with a wide range of technologies. Additionally, I have implemented and deployed multiple smart contracts in my freetime. 
- [ ] **_How you got first into Ethereum_:** I learned about the DAO hack in a security class I took during my bachelors degree. After following the space for multiple years, I started developing my first interfaces/contracts last year. 
- [ ] **_What brings you to ETHBerlin_:** I am excited to meet like-minded people in the Ethereum community and hope to be able to contribute to an interesting project. 

## Skills

_Tell us what your skills are:_

- [ ] Core Blockchain Development (Go, C++, Rust)
- [x] Smart Contracts (Solidity, Vyper)
- [x] DApps, Web3.JS (JavaScript, CSS)
- [ ] Blockchain Operations, Infrastructure
- [ ] Game theory, Crypto-Economics
- [x] Design, User Experience
- [ ] Project Management
- [ ] _Other_: ...

## Communication

_Consider leaving your personal Matrix address so that the team can contact you off GitHub._

- [ ] _Matrix handle_: `@niklasnatter:matrix.org`
- [ ] _Twitter_: https://twitter.com/niklasnatter

**Comment by elstongun** [comment]
Dm'd
