### ISSUE TITLE
[LFT]: Web3 Full Stack Engineer looking for a team

### ISSUE THREAD

**Issue by firattale** [ethb3rlin/find-a-team#17]
## Background

_Talk a little about yourself:_

- [ ] _Who you are_: I am an experienced frontend developer, and transitioning to web3.
- [ ] _What you do_: I work for a web2 company full-time and makind web3 projects as a freelancer.
- [ ] _How you got first into Ethereum_: I bought my first ETH in 2019 and want to explore more in 2021, I got hooked to smart contracts and want to become a full time smart contract developer.
- [ ] _What brings you to ETHBerlin_: I live in Berlin, so this could be a good chance to meet like minded people.

## Skills

_Tell us what your skills are:_

- [ ] Core Blockchain Development (Go, C++, Rust)
- [x] Smart Contracts (Solidity, Vyper)
- [x] DApps, Web3.JS (JavaScript, CSS)
- [ ] Blockchain Operations, Infrastructure
- [ ] Game theory, Crypto-Economics
- [ ] Design, User Experience
- [ ] Project Management
- [ ] _Other_: ...

## Communication
_Consider leaving your personal Matrix address so that the team can contact you off GitHub._
https://github.com/firattale
firatstory@gmail.com
- [ ] _Matrix handle_:
@firatstory

_Note that this is only a template, feel free to talk about anything you want teams to know!_

**Comment by elstongun** [comment]
Dm'd on Matrix
