### ISSUE TITLE
[LFT]: PM & Data Analyst looking for a Team

### ISSUE THREAD

**Issue by muhuuh** [ethb3rlin/find-a-team#19]
## Background

_Talk a little about yourself:_

I am now in the space since ’17 and aim to contribute to disrupting the incumbent system. I enjoy data analytics and won a few onchain analytics competitions with Dune dashboards. In addition to PostgreSQL & Redshift, I also have some experience with python, react.js. and js.

In general, I have an econ background and I am passionate about Game Theory. I wrote a few essays and a book about the impact of decentralisation of society from a game theoretical perspective. During the day, I am also a team lead at a FANG company which helped me gather experience as PM, coordinating projects and shipping products from the “customer first” perspective.

_In Summary_

- [x] _Who you are_:  PM & Data Analyst with a passion for Game Theory and knowledge in python & react.js
- [x] _What you do_:  I wone a few on chain data analytics competition, wrote a book about Game Theory and I am currently improving my skills in react.js. I am building a skill set with the aim to disrupt the incumbent system thanks to web3
- [x] _How you got first into Ethereum_: Through deep diving tinto topcs around decentralisationa and Game Theory in 2017
- [] _What brings you to ETHBerlin_: I want to find like minded people, build and contribute with them with the goal of building a products that improve the live of others and/or disrupt the current gate keepers.

## Skills

_Tell us what your skills are:_

- [x] Data Analytics
- [ ] Core Blockchain Development (Go, C++, Rust)
- [ ] Smart Contracts (Solidity, Vyper)
- [ x ] DApps, Web3.JS (JavaScript, CSS)
- [ ] Blockchain Operations, Infrastructure
- [x] Game theory, Crypto-Economics
- [ ] Design, User Experience
- [x] Project Management
- [ ] _Other_: ...

## Communication

Feel free to reach out, for example also 
- on twitter: @aranimontes
- on element: @arani:matrix.org

**Comment by EdsonAlcala** [comment]
hey I can do smart contracts and full stack development. I have been in the space since '17 too.
