### ISSUE TITLE
[NEW]: thegraph protocol or pooltogether support for rotki

### ISSUE THREAD

**Issue by step21** [ethb3rlin/find-a-team#25]
## Introduction

_Talk a little about yourself:_

- [ ] _Who you are_: Legal Engineer, mainly worked with controlled natural languages and computable contracts
- [ ] _What you do_: Currently between thesis and the next job. Have in the past worked on smart contract projects, done security review for Lexon and others and did evaluation of crypto and other projects. Also did a Remix Plugin for Lexon.
- [ ] _How you got first into Ethereum_: Helped organize the first Berlin Eth Meetup, after meeting Eth people at btc meetups
- [ ] _What brings you to ETHBerlin_: Nostalgia and good memories, and looking for actual decentralization.

Looking to push decentralization forward based on open-source and local-first, with tracking as little data as possible.

## Idea description

_What is your idea? Give as many details as you possibly can._

rotki is a great local-first open-source based app to track crypto balances and other assets: [rotki homepage](https://github.com/rotki/rotki/) I think the team does a great job, but gitcoin grants, premium subscriptions and other funding and the limited time of developers can only go so far to implement and support all relevant features.
I have always wanted to contribute to rotki, and so maybe this hackathon is the right time to focus on this and get to a working version for a missing protocol or feature. My preferences would be thegraph protocol or pooltogether.
If this sounds great to you and you have relevant skills, please contact me.

## Skillset

_What skills do you need, or think you might need to implement the idea?_

- [ ] Core Blockchain Development (Go, C++, Rust)
- [ ] Smart Contracts (Solidity, Vyper)
- [ ] DApps, Web3.JS (JavaScript, CSS)
- [ ] Blockchain Operations, Infrastructure
- [ ] Game theory, Crypto-Economics
- [x] Design, User Experience
- [x] Project Management
- [x] _Other_: Application Development (Python), Backend Development (Python)

## Communication

_Consider leaving your personal Matrix address so that the team can contact you off GitHub._

- [ ] _Matrix handle_: @fl0_id:matrix.org

_Note that this is only a template, feel free to talk about anything you want teams to know!_

**Comment by LefterisJP** [comment]
Hey @step21 thanks for starting a rotki related hacking team!

Just for potential team member's shake let me link the issues you mention in rotki's repo.

- [Add support for GRT staking](https://github.com/rotki/rotki/issues/2044)
- [Add Pooltogether support](https://github.com/rotki/rotki/issues/1120)

Members of rotki's dev team, including me will be around the hackathon and some may even join rotki related teams. But our goal would be to help people like you hack in rotki :)

**Comment by chrishobcroft** [comment]
This is super interesting.

I would be interested in participating in this. I would also seek to add Livepeer / LPT Staking, and can guide analysis of the design of the mechanism.

**Comment by step21** [comment]
Thanks @LefterisJP  for chiming in.
Thank for your suggestion and thanks for your interest @chrishobcroft 

Livepeer looks super interesting. Probably it would be good to decide what to focus on based on how many people partcipate, as to also get something functional in the end.

**Comment by chrishobcroft** [comment]
Thanks @step21 there is definitely some novelty in both of Livepeer's protocols, the "continuous funding" delegated-PoS protocol, and the "probabilistic micropayments" payment protocol. Both protocols are deployed on Arbitrum Nitro.

These protocols have combined to successfully create a decentralised video transcoding network of 100 nodes (pending upgrades for expansion). A transcoding network is the backbone for a decentralised livestreaming network.

The dPoS currently has ~4,300 delegators, delegating 51% of all Livepeer Tokens (LPT) in issue.

![Screenshot_20220904-144615_DuckDuckGo](https://user-images.githubusercontent.com/2212651/188314198-8dc4ffd2-67e5-450c-8b12-18a461b535c5.png)
(source: [Livepeer Protocol Explorer](https://explorer.livepeer.org))

Further, there are 2,376,855 holders of LPT (source: [LPT on Etherscan](https://etherscan.io/token/0x58b6a8a3302369daec383334672404ee733ab239).

I can't probably add much in terms of Graph and Pooltogether, but I would be very happy to participate in this project if it were to deliver Livepeer feature in Rotki, and would also definitely then become a subscriber to the software.

**Comment by step21** [comment]
Well, tbh personally I do not care about the numbers Livepeer has. If you wanna work on it, that's enough.
However, good that you mention that it is on Arbitrum, as I think rotki does not have Arbitrum support so far and from my point of view, unless the team gets bigger, ideally with someone who knows both Arbitrum and at least python desktop apps in general, I fear it is not very realistic to add this over a weekend. Or do you think it is enough for you to do it?

**Comment by chrishobcroft** [comment]
I am not a developer, so I cannot do this alone.

If anyone does want to work on this, I am happy to collaborate, guide, and share details.

Would you prefer if I raised this as a separate issue, and allow you to focus on GRT and Pooltogether?

**Comment by step21** [comment]
Ok sure. It's fine for me to leave it in this issue, I just want to set realistic expectations.
