### ISSUE TITLE
[LFH]: EthMTP, a communication layer on top of Ethereum

### ISSUE THREAD

**Issue by Meyanis95** [ethb3rlin/find-a-team#26]
One of the big problem of Ethereum is lack of communication, you need to spend hours looking Discord and Twitter to not have the feeling to loose some piece of information and to keep updated about your favorite protocols' latest news. 
Also as a user, I want to protect myself and my privacy by not giving my personal email. 
Is it possible to have a way for Dapps and protocols to talk to their users and respect their privacy?!

EthMTP is the communication layer for Ethereum. You can authenticate with your ETH address and access an email address ((0x83j...7893@ethmtp.com), and start sending and receiving emails.

For this hack, we'll need to build:
- A Oauth 2.0 server for Ethereum login
- An SMTP server
- A login page
- Would be cool to work on a firewall solution to by default block all the senders. 
- Create subgroups based on Zk Badges (using Sismo for example)

## Team

For the moment I'm alone and searching for folks to join me on this hack :)
If you're a developer/designer and want to hack a communication layer on top of Ethereum, join the team.

## Skills Wanted

- [x] DApps, Web3.JS (JavaScript, CSS)
- [x] Design, User Experience
- [x] PHP, SMTP/IMAP protocols
- [x] Linux

## Communication

- [x] _Matrix handle_: @sinaxyz:matrix.org
- [x] _Twitter handle_: twitter.com/yanis_mezn

**Comment by yncyrydybyl** [comment]
This looks interesting. Are you also interested to do it with matrix instead of email?
