### ISSUE TITLE
[LFH]: Real-world asset NFTs - Fractional ownership of tokenised real estate

### ISSUE THREAD

**Issue by jcarbonnell** [ethb3rlin/find-a-team#30]
## Land Minis3 - Tokenized real estate investment platform
The Land Minis3 is an AI-augmented NFT marketplace for the fractional ownership of tokenized real estate. 

Tokenized real estate enables the performance and scalability of a socially distributed wealth-building protocol, for which we are gathering the greatest real estate club reimagining the rental business to reach financial freedom and wealth through real estate & crypto, applying proven investment strategies.

## Team
We are starting with a mixed team of 6 M/F folks all real-estate-blockchain enthusiasts with various skills in software development, digital marketing, product management, content writing, and real estate development. 

## Skills wanted

Still, some open positions to strengthen the developers' team. 
We're looking for programmers in Clarity, Python Django, and HTML.

- [ ] Core Blockchain Development (Go, C++, Rust)
- [x] Smart Contracts (Solidity, Vyper)
- [x] DApps, Web3.JS (JavaScript, CSS)
- [ ] Blockchain Operations, Infrastructure
- [ ] Game theory, Crypto-Economics
- [ ] Design, User Experience
- [ ] Project Management
- [ ] _Other_: ...

## Communication
https://www.linkedin.com/in/juliencarbonnell/
https://twitter.com/JCarbonnell

**Comment by 1olivier** [comment]
Hi Julien, your project looks pretty cool ! Let me know if I can be of any help.
