### ISSUE TITLE
[LFH]: Whistleblower (private Lens)

### ISSUE THREAD

**Issue by tiagofneto** [ethb3rlin/find-a-team#33]
## Pitch it!

Hello hackers!!

Whistleblower allows anyone from all over the world to privately and securely post on Lens any information that they find worth sharing. 
From conspiracy theories, to crushes, Whistleblower covers it all.

Join us in making the world a more transparent, fair and safe place for everyone!

## Team

We are 2 experienced hackers (multiple hackathon winners), with a very simple goal: democratize information flow.
Our skills range from development to product management.

## Skills wanted

We are looking for skilled team members that share the same values and goals as we do:
- [ ] UI/UX Designer
- [ ] Frontend Dev

## Communication

_Matrix handle_: tiagofneto @tiagofneto:matrix.org

**Comment by gabrielfior** [comment]
Hey, happy to discuss more about the project! Please write me on TG @wiskkkk
