### ISSUE TITLE
[NEW]: Web3-native Discord / OS for web3 orgs

### ISSUE THREAD

**Issue by banditen** [ethb3rlin/find-a-team#39]
## Introduction

_Talk a little about yourself:_

- [x] _Who you are_: Ex-venture investor in +60 early-stage startups, built 2 B2C software startups previously.  
- [x] _What you do_: Strategy, business development, and finance at a gaming fintech & web3 ReFi startup.
- [x] _How you got first into Ethereum_: By reading the first pre-released whitepaper of Aave in 2017.
- [x] _What brings you to ETHBerlin_: I love hackathons! Looking to build my own idea forward.

## Idea description

_What is your idea? Give as many details as you possibly can._

Discord, as one of the main operations management solutions for web3 projects, is not suitable for achieving long-term, sustainable growth for web3 projects due to it's core use-case. Discord isn't purposefully built for web3 projects, which means that different projects (especially DAOs) are not able to sustain an operational excellency over time due to the heavy load of scattered information.

Problem 1:
Lack of interoperability and effective decision-making: web3 ecosystem is pushing decentralised protocols and infrastructure forward, while management and participation of these projects are run on web2 solutions like Discord and Notion without limited flexibility.

Problem 2:
The entry-barriers for new entrants in projects grows exponentially the larger the project gets: setting up community onboarding flows in Discord and knowledge onboarding flows in Notion makes the whole process of joining a project overwhelming, which kills operational effectivity and diversity, thus leading to a long-tail of so called free riders in Discord communities.

Solution:
A flexible, open-source, operations management tool with integrated governance, communication, community and knowledge management. There should be an easy way to build web3 integrations on top of a central "intranet" that supports in effective decision-making without compromising the easiness of joining a community.

## Skillset

_What skills do you need, or think you might need to implement the idea?_

- [x] Core Blockchain Development (Go, C++, Rust)
- [X] Smart Contracts (Solidity, Vyper)
- [X] DApps, Web3.JS (JavaScript, CSS)
- [X] Blockchain Operations, Infrastructure
- [ ] Game theory, Crypto-Economics
- [X] Design, User Experience
- [ ] Project Management
- [ ] _Other_: ...

## Communication

_Consider leaving your personal Matrix address so that the team can contact you off GitHub._

- [ ] _Matrix handle_:

@banditen:matrix.org

**Comment by coffeeandsnacks** [comment]
@lummi:matrix.org

Being in the space for quite some time, I know the problem first hand and find the idea very intriguing. I have a background in business, but know Solidity and wrote a few Smart Contracts in the past. Curious to meet you in the next days, lummi
