### ISSUE TITLE
[NEW]: (collective ideation/brainstorming based) 'The Leap'

### ISSUE THREAD

**Issue by RizzeKnight** [ethb3rlin/find-a-team#40]
## Introduction
- For a bit of personal context, please see #38 
- For well over a decade now, I have been dreaming of us (yes, humans) truly _leaping_ into the future. Starting with Bitcoin and the general notion of & opportunities around blockchain tech, through 'years of Ethereum' and everything else in the space, into the present. It is simply amazing to see how far we already got. But we are still lagging behind. We need a lower bar of entry into the space, more privacy & security (e.g. less concessions to decentralization), but also more clever 'embedding' into society such as it simply IS, right now (and, in certain ways, simply HAS BEEN, for a very long time). The best & fastest innovation is rooted in what came before, NOT that which simply tries to 'break' and/or replace.
- Perhaps https://www.unigrid.org/ (and/or https://www.decentralized-internet.com/) could also provide some inspiration. If not for actual hacking/use, then perhaps at least for conceptualization (and potentially even 'what NOT to do').

## Idea description
- The basic idea is to _**brainstorm**_ a solution that will provide (at least the initial spark) of the aforementioned leap into the future. We need something REALLY viral (that makes all other buzzwords and hypes pale in comparison, obviously). I invite any & all of you to meet with me to discuss options, choose one, and see how far we can get during (let alone after??) the event.
- For now, I will refrain from (even more) info overload, and merely provide a few 'working titles' that I came up with. Please feel free to 'fork'. But please feel even more free to engage with me! :)

Railchain. BlockCart. DigiDo. Powerchain. The GC Lobby.

Piqued your curiosity? Let me know! Also, please be sure to share your own ideas - as said, especially a pre-event chat will help us get the most out of our mutual/respective creativity.

Either way, all the best to ALL! ^^

## Skillset

_What skills do you need, or think you might need to implement the idea?_

- [x] Core Blockchain Development (Go, C++, Rust)
- [x] Smart Contracts (Solidity, Vyper)
- [x] DApps, Web3.JS (JavaScript, CSS)
- [x] Blockchain Operations, Infrastructure
- [x] Game theory, Crypto-Economics
- [x] Design, User Experience
- [x] Project Management
- [x] _Other_: anything & everything that helps us to at least get started, then we'll take details from there

**Comment by tomyo** [comment]
Will back link what I think already got us exited, so others can follow along too.
https://github.com/ethb3rlin/find-a-team/issues/41

Meet you soon in the event!  :)
