### ISSUE TITLE
[NEW]: Censorship resistant geo-located messages that empowers anyone to have a voice

### ISSUE THREAD

**Issue by tomyo** [ethb3rlin/find-a-team#41]
## Introduction

- [x] _Who you are_: I'm a Frontend developer.
- [x] _What you do_:  Web development.
- [x] _How you got first into Ethereum_: I was volunteering ETH-Berlin². 
- [x] _What brings you to ETHBerlin_: I want to help bring web3 to the common user, and fight back the centralized model where everyone is in danger to get banned, censored or canceled by platforms, anytime for whatever reason.

## Idea description

Censorship resistant geo-located messages that empowers anyone to have a voice.
* I imagine this similar to a graffiti or a tag you can "leave" somewhere, and anyone can read.
* Anonymous by default: no fear to say anything.
* Then let's see how this can used in the most useful and fun way.

#### Some example use cases:
* Connect with people and information relevant to a location and time.
  - Thoughts, insights, opinions, free exchange of <you-name-it>, etc.
* Help a community / building / area be more connected (Can some one help/lend me X?)
  - Don't you find it strange we can easily connect around the globe, but we live surrounded by neighbors we don't ever know about?
  - We are missing great opportunities to connect with people around us, and empower our local communities.  

Note: I've seen some attempts on this idea, but all in a "sign-up with E-Copr SSO and give us your data" approach... we can do better!
 
## Skillset

_What skills are needed, or think are needed to implement the idea?_

- [ ] Smart Contracts
- [ ] DApps, Web3.JS (JavaScript, CSS)
- [ ] Blockchain Operations, Infrastructure
- [ ] Game theory, Tokenomics
- [ ] Design, User Experience
- [ ] Project Management
- [ ] UX
- [x] Web development (JS/HTML/CSS)

## Communication

- [x] _Matrix handle_: @tomyo:matrix.org
- [x] Telegram handle: @tomyo
- [x] Discord handle: tomyo#8846

Feel free to comment on this thread instead of DM me, so we can all know who's interested, giving a :+1: here should be enough to signal interest, then we can create a group somewhere.

Thanks for reading this far!

**Comment by RizzeKnight** [comment]
Awesome. Would be THE *perfect* foundation for an AR app (or ALL of them), at least down the line!

Also reminds me of further opportunity I thought about (a lot), before.

Hoping to connect with you (at least) on this - will throw you a quick DM. Good luck either way, great idea! :)

Inconsistency though between 'What needs to be defined' & 'Skillset'- should align 1:1 (?), maybe consider updating the post.

**Comment by tomyo** [comment]
[RizzeKnight](https://github.com/RizzeKnight), will update as you suggest, thanks for the comment!, ^_^

See you soon and let's keep the ball rolling. I don't think of this as "my idea", but as something it needs to exists, and what a better opportunity than this web3 hackaton to make it happen! (or take the first steps: forming a team aligned in the vision, and up for the challenge, :)

**Comment by PabloCastellano** [comment]
Sourcecode here: https://github.com/tomyo/locpost/
