### ISSUE TITLE
[NEW]: Exploring direct carbon offseting on Lens

### ISSUE THREAD

**Issue by Dakavon** [ethb3rlin/find-a-team#43]
## Introduction

We are in the midst of the climate crisis. 
Awareness and options for positive climate action should become visible more often. 

_Talk a little about yourself:_

Hi, it's niels.eth :wave:
I am a project manager, web3 enthusiast and Klimate. :seedling:
In my free time I became a solidity dev and started participating in hackathons beginning with ETHBerlinZwei.
Still writing code is not my daily job but a passion of mine. :robot: 

During ETHBerlin³ I would like to explore lens protocol and options to directly offset carbon credits (NCT).

## Idea description

NCT - a nature-based carbon credit token from **Toucan** protocol - became lately a native currency on lens.
We should develop/extend a **Lens** app that simply **retires carbon credits**. 

E.g. via Lens Collect on Lenster (https://lenster.xyz/)
Retiring carbon credits may be also possible directly during selling content to frens via Lens Collect instead of the authors receive NCTs as a payment and afterwards need to claim TCO2s and retire them manually.

![Lenster+Toucan](https://user-images.githubusercontent.com/3898916/190637054-acd334f8-040f-40d9-8413-00b47ab243c4.png)

https://blog.toucan.earth/carbon-currency-lens/
https://docs.lens.xyz/docs/collect

## Skillset

_What skills do you need, or think you might need to implement the idea?_

- [ ] Core Blockchain Development (Go, C++, Rust)
- [x] Smart Contracts (Solidity, Vyper)
- [x] DApps, Web3.JS (JavaScript, CSS)
- [ ] Blockchain Operations, Infrastructure
- [ ] Game theory, Crypto-Economics
- [x] Design, User Experience
- [ ] Project Management
- [ ] _Other_: ...

## Communication

- [x] _Matrix handle_:   @niels_:matrix.org
- [x] _Discord_:   Niels#8358

Get in touch if you are interested in exploring this further together. :handshake:

**Comment by 0xAurelius** [comment]
Hey mate, just wanted to point you to my previous work developing a Collect module that retires carbon using KlimaDAO's retirement aggregator

https://github.com/lens-protocol/core/pull/36

You should be able to straightforwardly extend it to support NCT, will definitely save you a lot of wrangling with the contract calls required to retire credits

**Comment by Dakavon** [comment]
@0xAurelius You are truly a gentleman, as always :)
Thanks for pointing me in this direction! :deciduous_tree:
