### ISSUE TITLE
[NEW]: a frontend for dmap, the minimalistic immutable on-chain registry

### ISSUE THREAD

**Issue by chaserene** [ethb3rlin/find-a-team#49]
## Introduction

_Talk a little about yourself:_

- [ ] _Who you are_: chaser
- [ ] _What you do_: ecosystem and technology research 
- [ ] _What brings you to ETHBerlin_: Ross Ulbricht is still in prison

## Idea description

dmap is a key-value registry on Ethereum. think ENS's .eth root zone, but it's simple (30 lines of Solidity code), governanceless, tokenless, programmable and immutable/finalized.

github: https://github.com/dapphub/dmap
awesome dmap: https://github.com/dapphub/awesome-dmap
short intro: https://twitter.com/chaserxy/status/1556393981268922368
namezone guide: https://ricobank.github.io/how-to/make-a-namezone
dmap matrix chat: https://matrix.to/#/!fPkCITVoalKnkTGhyf:matrix.org (**not** the chat for this hackathon idea, rather a place to discuss the underlying system)
dmap-testing: https://github.com/dmfxyz/dmap-testing/

since this registry is practically as secure as Ethereum itself, it can have far-reaching implications and deserves to have **a frontend that allows users to interact with it**. my idea is to create a secure graphical web UI that lets people do nearly everything that is possible in the system: zone registration, name resolution, value changes, name locking, zone logic deployment, and whatever other use case that can come to mind.

## Skillset

_What skills do you need, or think you might need to implement the idea?_

- [ ] Core Blockchain Development (Go, C++, Rust)
- [x] Smart Contracts (Solidity, Vyper)
- [x] DApps, Web3.JS (JavaScript, CSS)
- [x] Blockchain Operations, Infrastructure
- [ ] Game theory, Crypto-Economics
- [x] Design, User Experience
- [ ] Project Management
- [x] _Other_: security-conscious, complexity-reducing mindset

## Communication

- [ ] _Matrix handle_: @chaserene:matrix.org

**Comment by JamesLefrere** [comment]
Hey @chaserene I would love to join. dsuite tools deserve a usable frontend. Here's my profile: https://github.com/ethb3rlin/find-a-team/issues/51
