### ISSUE TITLE
[LFT]: Core Dev is looking for a team.

### ISSUE THREAD

**Issue by pepyakin** [ethb3rlin/find-a-team#57]
## Background

Hey! My name is Sergei. 

I am a core dev at paritytech. It's been quite a while and I did a lot of stuff there, but mostly it's wasm and Rust. My first experience with Ethereum was not so long before the DAO. I guess I just liked learning stuff, and I got hooked by EVM. I am coming to EthBerlin for new experiences. Specifically, this is my first hackathon. Be gentle.

## Skills

- Rust,
- WebAssembly,
- Protocol design. Designed the first versions of the smart contract for Substrate, now known as Ink!.
- I had some experience with EVM, and Solidity a while ago.
- Obviously, Polkadot/Substrate stack.
- Long tail of different tech: various languages (JS, Haskell, Java, etc ...), rudimentary devops, worked with different bytecode VMs and compilers.

## Communication

_Matrix handle_: `@pepyakin:matrix.parity.io`

**Comment by etzm** [comment]
Hey!  Checkout: https://github.com/ethb3rlin/find-a-team/issues/59

**Comment by pepyakin** [comment]
Hey everyone! I found a team!
