### ISSUE TITLE
[NEW]: [LFH] Use Hyperlane's API to build in the Interchain!

### ISSUE THREAD

**Issue by Skunkchain** [ethb3rlin/find-a-team#62]
## Introduction

We're Hyperlane, the interchain messaging platform. With Hyperlane's messaging API you can easily and securely communicate between blockchains, empowering you to build interchain applications. Hyperlane's Interchain Accounts allow you to perform actions on distant chains without ever having to deploy contracts on those chains. 

## Idea description
We have a bunch of ideas about what you could do with Hyperlane, but to help you narrow it down here are some, going from more general to more specific:

- You could be passing messages or assets. You could be making cross-chain view calls or oraclize data between blockchains. There is really no end to what you could build, but given that time is of the essence you don’t want to expand scope too much.
- A great way to shoot for the top prize is to attempt to make an interchain version of a popular app, i.e. an interchain Compound  or Sudoswap.
- DeFi related
    - You could use our Interchain Accounts API to create an app that allows for interchain swaps without having to deploy any contracts on remote chains.
    - You could create an interchain Stableswap, accepting deposits of assets on multiple chains and creating unified liquidity pools.
    - You could create a contract that allows you to control multiple SAFEs or DAOs on remote chains. Using Interchain Accounts you could do this without having to deploy any additional logic on the receiving chains.
    - You could create interchain payment streaming contracts, collecting deposits on a number of chains and directing assets to 
- NFT related
    - You could create an interchain minting contract that acts as a load balancer between chains, i.e collecting orders on several chains (with lower fees or higher throughput) and executing the mint on a different chain.
    - You could create an interchain nft collection where the NFTs have different properties based on the chain they’re currently on.
-  Infrastructure
    - With respect to infrastructure, here’s a chance to build infrastructure either for Hyperlane or build infrastructure for other protocols that uses Hyperlane.
    - For example, a previous Hyperlane prize winner built infrastructure that supports Hyperlane relayers

## Communication & Resources

You can [read our docs](https://docs.hyperlane.xyz) or [join our discord](https://discord.gg/RE5ejPtJ3G) to learn more! We want to hear all your feedback and questions.

**Comment by bowd** [comment]
Hey hey! I've turned UniswapV2 pools into cross-chain pools using Hyperlane! https://devfolio.co/projects/hyperswap-f5da
