### ISSUE TITLE
[LFT]: Fullstack dev. looking for projects around privacy, Zk and social apps

### ISSUE THREAD

**Issue by Meyanis95** [ethb3rlin/find-a-team#7]
## Background

_Talk a little about yourself:_

- [x] _Who you are_: 
My name is Yanis, I'm a former product manager and learning coding for 10 months. I'm passionate about web3 and hacked at a lot of ETHGlobal hackathons and won some of them. 

- [x] _What you do_: 
I'm working on a frontend for Gnosis Safe multisig, trying to build the best experience to own items with friends. 

- [x] _How you got first into Ethereum_: 
I'm into Ethereum since the beginning of 2021, I first invest and then discovered the decentralization and ownership enabled by it and quit my job to focus on building Dapps.

- [x] _What brings you to ETHBerlin_: 
I want to learn and meet people interested in Zk and privacy.

## Skills

_Tell us what your skills are:_

- [ ] Core Blockchain Development (Go, C++, Rust)
- [x] Smart Contracts (Solidity, Vyper)
- [x] DApps, Web3.JS (JavaScript, CSS)
- [ ] Blockchain Operations, Infrastructure
- [ ] Game theory, Crypto-Economics
- [x] Design, User Experience
- [ ] Project Management
- [ ] _Other_: ...

## Communication

_Consider leaving your personal Matrix address so that the team can contact you off GitHub._

- [x] _Matrix handle_: @sinaxyz:matrix.org
- [x] _Twitter handle_: twitter.com/yanis_mezn

_Note that this is only a template, feel free to talk about anything you want teams to know!_

**Comment by elstongun** [comment]
Dm'd on Matrix

**Comment by allkindsxyz** [comment]
DMed on Matrix
