### ISSUE TITLE
[LFT]: Full Stack Solidity engineer happy to join your team!

### ISSUE THREAD

**Issue by qedric** [ethb3rlin/find-a-team#84]
## Background

_Talk a little about yourself:_

I'm a full stack blockchain/web3 engineer with a background in enterprise architecture. 
I'm from New Zealand, based in Berlin
I first got into Ethereum around 2015, and I'm attending ETHBerlin to learn, to connect, and to hack!

## Skills

_Tell us what your skills are:_

- [ ] Smart Contracts (Solidity)
- [ ] DApps, Web3.JS (TypeScript, Node, NextJS, React, hardhat, ethers, viem)
- [ ] Design, User Experience
- [ ] Project Management
- [ ] _Other_: ...

## Communication

Looking forward to seeing you very soon!

**Comment by madvil2** [comment]
My name is Konstantin and along with Jade, we are looking to build a decentralized student ID system designed by students, for students. This system will simplify international student transitions and offer reliable credential verification for professional recruitment.

Jade specializes in UX/UI design and business modeling, while I handle the frontend development using React and TypeScript. We are seeking support from a web3 developer with experience in zkProof to join our team.

If you are passionate, we would love to have you on board!

**Comment by qedric** [comment]
Hi @madvil2 I'm interested, but tbh I don't have any experience working with zk proofs - happy to discuss and see if there is a fit tho!

**Comment by madvil2** [comment]
We can meet at the venue, when will you come?

**Comment by qedric** [comment]
I will be there in about 1 hour, you?

**Comment by madvil2** [comment]
We are close to place, do you have a telegram? Write me @madvil2

**Comment by qedric** [comment]
I'm @qedric on telegram

**Comment by reisepass** [comment]
If your interested in the Infrastructure DePin category...

Some stuff i'v been thinking of on the theme of breaking that AWS Azure duopoly  and letting smaller player compete:

- Decentralized  KeyVault KeyStore .  If we want to enable decentralized infra providers a common generic decentralized key-sharing mechanism would be needed.   
- Anonymize the server renting / provisioning process by creating anonymising terraform adapter maybe through onion but remaining e2ee
-Mega simple but needed to compete with utility of credit cards :  easy recurring payments with spending control for variable monthly cost workloads 

@scirock  on telegram

**Comment by qedric** [comment]
Joined a team!
