### ISSUE TITLE
[LFH]: Make a Decentralized Dapp to Force Exit From Rollups (need a designer!)

### ISSUE THREAD

**Issue by outsider-analytics** [ethb3rlin/find-a-team#9]
## Introduction

_Talk a little about yourself:_

- [x] _Who you are_:  I'm a data scientist working in the ZK proof space
- [x] _What you do_:  I collect data on zk circuits on Ethereum on a grant from the Ethereum Foundation
- [x] _How you got first into Ethereum_: DEFI (was working in Tradfi)
- [x] _What brings you to ETHBerlin_: ZK Summit, Dunecon, and the community!

## Idea description

With the recent centralized attacks on Tornado Cash, there is a legit fear that central govs will attempt to force validators to censure txs.  Where this is most acute on Ethereum is the currently very centralized blockchains on L2s.  Rollups claim to be more secure than validiums due to storing state on L1.  This allows users who's transactions are being censured to submit a withdrawal request directly to the L1 rollup contract and bypass the censuring from the L2.  For instance zkSync has an alternative withdrawal located here https://withdraw.zksync.io/.

In the circumstance that zkSync becomes evil and censures transactions, no one should trust their front end to help them (obviously).  For this project, I would like to create a fully unstoppable dapp running on IPFS to allow a front end for users to force exit from L2s.  This would allow non expert users (who can't just write their own contracts) to safely exit from Rollups who have been forced into censuring txs on the L2 blockchain.

Stretch Goal:  In the case of a frozen L2, the user would need to provide a proof to the L1 rollup contract in order to trigger withdrawals.  The stretch goal is to allow the user to generate the necessary proof and submit the tx to the rollup contract for forced withdrawal of the L2.  This would require someone who can build a system to generate the proof using the open source circuits, and consistent access to a ton of compute to generate the proof for the end user.  But that's why its a stretch goal :)

At the end of the day what good is the ability to force exit a rollup if the front end to do so is on the centralized website?  This should be relatively simple, but damn does it need done BEFORE these centralized L2s get orders from the government!  Help me make this a reality and take a meaningful step towards helping non devs stay decentralized.

## Skillset

_What skills do you need, or think you might need to implement the idea?_

We are all full and ready to crank :)

- [ ] Core Blockchain Development (Go, C++, Rust)
- [ ] Smart Contracts (Solidity, Vyper)
- [ ] Dapps, Web3.JS (JavaScript, CSS)
- [] Blockchain Operations, Infrastructure
- [] Game theory, Crypto-Economics
- [x] Design, User Experience
- [ ] Project Management
- [ ] _Other_: Zk proof generation experts

## Communication
Discord: Outsider Analytics#9451
Telegram: outsideranalytics
- [x] _Matrix handle_: outsideranalytics @outsideranalytics:matrix.org

_Note that this is only a template, feel free to talk about anything you want teams to know!_

**Comment by chrishobcroft** [comment]
Consider serving the dApp from Swarm, and use bzz.link URLs, so that everything can be controlled and governed by the same keys / DAOs / multisigs etc. Adding a second key into the stack just for IPFS just doesn't feel worthwhile.

Cc. @costgallo

**Comment by outsider-analytics** [comment]
@chrishobcroft @costgallo
Awesome thanks so much for the suggestion! I'm unfamiliar with all of your terms and I'm excited to do a deep dive. 🙂 Do you have any examples of similar projects to study if you have a sec?

**Comment by AuHau** [comment]
@outsider-analytics depends on how deep you want dive, you can find white-paper or even a whole academic book describing how Swarm works on our website ethswarm.org. A nice article that presents maybe an easier-to-consume understanding of Swarm is also [here](https://hackernoon.com/a-brief-introduction-to-ethereum-swarm).

If you want to play around with uploading dApps to Swarm, the easiest way is through our [Gateway](https://gateway.ethswarm.org/) which allows you to upload 10MB data/sites and gives you also the mentioned bzz.links. Otherwise you can try to run your own local light node with our [Swarm Desktop](https://desktop.ethswarm.org/) in order to upload more data.

Generally, ethswarm.org is a good entry point to learn more about Swarm ;-) Feel free to join our Discord if you have any questions: https://discord.com/invite/GU22h2utj6

**Comment by outsider-analytics** [comment]
@AuHau Awesome, thank you! I'll check it out

**Comment by chrishobcroft** [comment]
Why closed?

**Comment by outsider-analytics** [comment]
@chrishobcroft The team is filled up (So I closed it). But we are definitely still full steam ahead 🙂

**Comment by chrishobcroft** [comment]
Good news! Good luck!
